### PR TITLE
Get metadata from streaming

### PR DESCRIPTION
**Pull request by cjamcu**
Hi, I need to know the title of the song that was playing. To do this, create a stream and the native implementation so that it allows you to know this in real time.

### CODE REVIEW

**Comment by Sithira** [comment]
Hi @cjamcu,

Is this for Shoutcast? 🤔

**Comment by cjamcu** [comment]
@Sithira yes :)

**Comment by Sithira** [comment]
@cjamcu can you PR this to the dev branch? I have some changes to source in dev branch

**Comment by cjamcu** [comment]
@Sithira ok. I created new pull request to dev branch.

**Pull request closed without merging**
